### ISSUE TITLE
Reorder menu items

### ISSUE THREAD

**Issue by davbyr** [British-Oceanographic-Data-Centre/COAsT-site#11]
Reorder menu items to be more logical. E.g.:

Overview
Getting Started
Contributing: COAsT
Contributing: Documentation
Reference

**Comment by thogar-computer** [comment]
@davbyr what are you wanting to do here? Add a new menu idea, so there are 2 contributing sections?

**Comment by davbyr** [comment]
@thogar-computer Nevermind -- I figured it out! Thanks anyway.
