### ISSUE TITLE
Example Page

### ISSUE THREAD

**Issue by thogar-computer** [British-Oceanographic-Data-Centre/COAsT-site#4]
on page 
https://british-oceanographic-data-centre.github.io/COAsT/docs/examples/example-page0/

Add python tag to embed code to allow colour coding to show

<pre>
``` python
```
</pre>

<table>
<tr>
<td> with tag </td> <td> without tag</td>
</tr>
<tr>
<td>

``` python
import coast
sci = coast.NEMO()
```

 </td>
<td>

```
import coast
sci = coast.NEMO()
```

</td>
</tr>
</table>

**Comment by jpolton** [comment]
On it

**Comment by jpolton** [comment]
Oooh pretty

**Comment by jpolton** [comment]
The CRPS example can be beautified with a python tag

**Comment by davbyr** [comment]
@jpolton Done -- and updated to include new observation class setup and new branch. Did it using the Edit Page button, but promise to figure out the Hugo stuff tomorrow.
