### ISSUE TITLE
Example Page

### ISSUE THREAD

**Issue by thogar-computer** [British-Oceanographic-Data-Centre/COAsT-site#9]
hi @davbyr
As a heads up, it is best not to include local paths within your examples scripts. it is a potential security issue for you and wouldn't help an external user - currently not a massive issue and can wait for y'all to get Hugo setup and working locally :)

**Comment by davbyr** [comment]
@thogar-computer Very true. I had been removing the paths but that latest one was a quick upload so it slipped my mind...
