### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by thogar-computer** [British-Oceanographic-Data-Centre/COAsT-site#97]
Neeed to example that the testing (i.e import coast) will not work if the user has followed the development part only... do ```import coast``` require the user to install coast from conda (or pip)

**Comment by thogar-computer** [comment]
https://github.com/British-Oceanographic-Data-Centre/COAsT/issues/508

**Comment by soutobias** [comment]
I added one more step to the development part:

"
Then build a python environment:

```
conda env update --prune --file environment.yml 
conda activate coast
```

The last step is to intall the coast package on this environment:

```
pip install -e .
```
"
